/**
 * \file DeclarativeInputEngine.h
 *
 * \brief Declaration of CDeclarativeInputEngine
 *
 * \author Uwe Kindler
 * \date 08/01/2015
 *
 * Copyright (c) 2015 Uwe Kindler
 */

#pragma once

#include <QObject>
#include <QRect>
#include <qqml.h>

struct DeclarativeInputEnginePrivate;

/**
 * The input engine provides input context information and is responsible
 * for routing input events to focused QML items.
 * The InputEngine can be accessed as singleton instance from QML
 */
class DeclarativeInputEngine : public QObject
{
    Q_OBJECT
    QML_SINGLETON

    // clang-format off
    /** The geometry of the currently visible keyboard in screen coordinates. */
    Q_PROPERTY(QRect keyboardRectangle READ keyboardRectangle WRITE setKeyboardRectangle NOTIFY keyboardRectangleChanged FINAL)

    /** Indicates whether the keyboard is currently animating (e.g., opening or closing). */
    Q_PROPERTY(bool animating READ isAnimating WRITE setAnimating NOTIFY animatingChanged FINAL)

    /** Current input mode, e.g., Letters or DigitsOnly. \sa InputMode */
    Q_PROPERTY(InputMode inputMode READ inputMode WRITE setInputMode NOTIFY inputModeChanged FINAL)

    /** True if the next character should be uppercase (shift pressed). */
    Q_PROPERTY(bool uppercase READ isUppercase NOTIFY shiftStateChanged FINAL)

    /** True if the keyboard is in symbol mode (e.g., showing punctuation). */
    Q_PROPERTY(bool symbolMode READ isSymbolMode WRITE setSymbolMode NOTIFY isSymbolModeChanged FINAL)

    Q_PROPERTY(ShiftState shiftState READ shiftState WRITE setShiftState NOTIFY shiftStateChanged FINAL)

    /** Whether the keyboard automatically capitalizes the first letter of a sentence. */
    Q_PROPERTY(bool autoCapitalize READ isAutoCapitalize WRITE setAutoCapitalize NOTIFY isAutoCapitalizeChanged)
    // clang-format on

public:
    /**
     * Input modes that determine which character set is active.
     */
    enum InputMode
    {
        Letters,   ///< Alphabetic keys (letters)
        DigitsOnly ///< Numeric keypad (digits only)
    };
    Q_ENUM(InputMode)

    enum ShiftState
    {
        ShiftOff,
        ShiftOn,
        CapsLock
    };
    Q_ENUM(ShiftState)

    /**
     * Constructs a declarative input engine with the given parent.
     */
    explicit DeclarativeInputEngine(QObject* parent = nullptr);

    /**
     * Destructor.
     */
    virtual ~DeclarativeInputEngine();

    /**
     * Returns the current keyboard rectangle in screen coordinates.
     */
    QRect keyboardRectangle() const;

    /**
     * Returns true if the keyboard is currently animating.
     */
    bool isAnimating() const;

    /**
     * Sets the animating status. Used during UI transitions to prevent
     * interference with ongoing animations.
     */
    void setAnimating(bool animating);

    /**
     * Returns the current input mode.
     * \see InputMode for possible values.
     */
    InputMode inputMode() const;

    /**
     * Sets the current input mode.
     * \see InputMode for possible values.
     */
    void setInputMode(InputMode mode);

    /**
     * Returns true if uppercase (shift) is active.
     */
    bool isUppercase() const;

    ShiftState shiftState() const;

    void setShiftState(ShiftState state);

    /**
     * Returns whether auto-capitalization is enabled.
     */
    bool isAutoCapitalize() const;

    /**
     * Sets whether auto-capitalization is enabled.
     * \param autoCapitalize - true to enable, false to disable.
     */
    void setAutoCapitalize(bool autoCapitalize);

    /**
     * Returns true if symbol mode is active.
     */
    bool isSymbolMode() const;

    /**
     * Sets the symbol mode state.
     */
    void setSymbolMode(bool symbolMode);

    /**
     * Simulates a key click on the virtual keyboard. Not yet fully implemented.
     * \param key          Qt key code
     * \param text         Text generated by the key
     * \param modifiers    Keyboard modifiers (Shift, Ctrl, etc.)
     * \return true if the event was accepted by the input engine
     */
    Q_INVOKABLE bool virtualKeyClick(Qt::Key key, const QString& text, Qt::KeyboardModifiers modifiers);

    /**
     * Informs the engine about the current keyboard rectangle. This should be
     * called whenever the keyboard's geometry changes (e.g., during resizing
     * or repositioning).
     */
    Q_INVOKABLE void setKeyboardRectangle(const QRect& Rect);

signals:
    /** Emitted when the keyboard rectangle changes. */
    void keyboardRectangleChanged();

    /** Emitted when the animating property changes. */
    void animatingChanged();

    /** Emitted when the input mode changes. */
    void inputModeChanged();

    /** Emitted when the shift state changes. */
    void shiftStateChanged();

    /** Emitted when the symbol mode state changes. */
    void isSymbolModeChanged();

    /** Emitted when the auto-capitalization setting changes. */
    void isAutoCapitalizeChanged();

private:
    DeclarativeInputEnginePrivate* d;

    friend struct DeclarativeInputEnginePrivate;

private slots:
    /**
     * Internal slot called when an animation finishes.
     * Used to update the animating property accordingly.
     */
    void animatingFinished();
};
