#pragma once

#include <QtCore/qglobal.h>

#if defined(MOCKUPVIRTUALKEYBOARD_LIBRARY)
#define MOCKUPVIRTUALKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#define MOCKUPVIRTUALKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif
